# Generated by Django 4.2.7 on 2024-05-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vendor')),
            ],
        ),
    ]
